### ISSUE TITLE
Standardize on Colours for Wind: Use Beaufort Scale

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#104]
I have used 
https://en.wikipedia.org/wiki/Beaufort_scale for colour coding the thresholds for Wind 
see Current Wind on Mount Ceder Weather Station : https://dashtweak.com/dashboards/15

km/h: 2,5,11,19,28,38,49,61,74,88,102,117
m/s: 0.5,1.5,3.3,5.5,7.9,10.7,13.8,17.1,20.7,24.4,28.4,32.6
#FFFFFF,#AEF1F9,#96F7DC,#96F7B4,#6FF46F,#73ED12,#A4ED12,#DAED12,#EDC212,#ED8F12,#ED6312,#ED2912,#D5102D

Maybe good to use the same for the Wind Bars?
It is probably unlikely to measure winds in excess of 17m/s ? so the colour range might be a bit flat, but rather stick to a standard.

**Comment by rochecompaan** [comment]
I guess this implementation is no longer required since we modified the wind arrow chart to show the wind speed with a line chart. Perhaps we can make bar charts an option in the future.

**Comment by GronumSmith** [comment]
Agree, lets postpone

**Comment by rochecompaan** [comment]
No longer relevant.
