### ISSUE TITLE
Make sure about wind directions in wind arrows

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#105]
For Akkerdal (switched temporarirly from MountCeder on https://dashtweak.com/dashboards/15 

![image](https://user-images.githubusercontent.com/35992133/79129786-1c3ca100-7da6-11ea-81e5-3ea6445cd209.png)

In afternoon of 11-04-2020 DashTweak shows arrows as coming from East (e.g. 280 Deg)

But on Grafana, whereas the wind direction is shown as varying between 220 and 310 (correct) the red dots (also 14:00-22:00) on the Windrose indicate that wind came from West (this is probably correct as the NW was bringing rain with the cold front)
Pleas check how direction is mapped/handled for the arrows! should be same as Grafana  Windrose... {BTW: Is this a standard?} 0= north, 90 = East see,s so https://en.wikipedia.org/wiki/Wind_rose
![image](https://user-images.githubusercontent.com/35992133/79129983-7f2e3800-7da6-11ea-9919-4a232a2ab986.png)

**Comment by GronumSmith** [comment]
Revisiting this: 
In DT the following was captured 
https://dashtweak.com/dashboards/50
![image](https://user-images.githubusercontent.com/35992133/91444838-9b260800-e875-11ea-874a-c80e2af17b14.png)
So values in CSV matches that displayed in DT.   i.e. @12h50
In Grafana at 12h50 it looks like this
![image](https://user-images.githubusercontent.com/35992133/91444999-cc9ed380-e875-11ea-97b5-83af578968ec.png)

The convention used (in Grafana) for a WindRose is 0 degrees is N, 180 degrees is S. clockwise increase (as per https://en.wikipedia.org/wiki/Wind_rose)
It seems as if DT i.e. 0 and 360 degrees = S, and 180 = N ?? 


Side comment: when we had bars for wind strength it seemed as if there were syncronized jumps (aggregation of data), now that the wind strength is done with lines both the strength and the direction values (read from vertical slider) change, one of the consequences is that the value read from the slider does not necessarily coincide with the arrow direction??  

Links to Wind Rose and arrows: 
https://www.meteoblue.com/en/weather/historyclimate/climatemodelled/convention_south-africa_1012817
https://www.epa.gov/sites/production/files/2019-01/documents/how_to_read_a_wind_rose.pdf

**Comment by GronumSmith** [comment]
BTW: What aggregation (or how) is done currently to get Arrow direction in DT and how is that related to the 

For Group Interval on Hour Time range it seems as if the arrows are every 10min, even though I set it on 5 min
![image](https://user-images.githubusercontent.com/35992133/91447010-78e1b980-e878-11ea-9f51-ae97c3f2e1c3.png)
Likewise on Week time range and with Group Intervals set @ 5min for Week this is the result 
![image](https://user-images.githubusercontent.com/35992133/91447199-b2b2c000-e878-11ea-9b65-6c84b05278b6.png)
see also 
![image](https://user-images.githubusercontent.com/35992133/91447322-d5dd6f80-e878-11ea-8435-473747a4468c.png)
seems like 30min aggregation and display interval for week setting?
It also seems as if the interval of arrows displayed is dynamic depending on the width of window (as can be expected) but maybe just have a look at this again or lets discuss.

**Comment by rochecompaan** [comment]
@GronumSmith can test to see if this working now, please?

With regards to the interval, it is exactly what you specify but if your interval results in two arrows being drawn over each other, arrows will be omitted in the display to prevent a swarm of arrows being drawn on top of each other. In other words, the algorithm will only render the next arrow if it is determined that it won't overlap with the previous one.

**Comment by GronumSmith** [comment]
Direction is correct! Spacing of arrows, OK lets see how it works and reopen if required
