### ISSUE TITLE
Map visualisation

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#107]
Add map to dashboard:

* Add "locations" to map  (click on map to capture GPS coordinate)
* Each location has GPS coordinate, label, thresholds, text colours, marker colours, query, URL (links to dashboard), tags

**Comment by nvernooy** [comment]
Map visualisation with pins and measurements in popup

![image](https://user-images.githubusercontent.com/5332516/93184898-14aa6b00-f73d-11ea-98a8-732be4da4c4e.png)
![image](https://user-images.githubusercontent.com/5332516/93184995-2e4bb280-f73d-11ea-9086-28d299e5b100.png)

**Comment by nvernooy** [comment]
Updated icons, added measurement selector, wind arrows show direction

![image](https://user-images.githubusercontent.com/5332516/93436207-c32fe680-f8ca-11ea-9a32-b80124aa3ceb.png)
![image](https://user-images.githubusercontent.com/5332516/93436277-dc389780-f8ca-11ea-8b44-e99ea1345b7a.png)

**Comment by rochecompaan** [comment]
I'm closing this issue since we have implemented maps and have more specific issues relating to maps logged already.
