### ISSUE TITLE
Variables for Collections

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#157]
We have Variables for Dashboards (see https://github.com/upfrontsystems/izinto-angular/issues/13) but there is a definite need to make variables more generally available e.g. for a Weather Station Site we would e.g. like to change ONLY the Installation_ID and then all the dashboards will be updated.

**Comment by nvernooy** [comment]
Added variables to a collection.
Variables in a collection can be added and edited same as in a dashboard.
The collection variables will be formatted into queries as usual, but a dashboard variable with the same name has higher priority and will override the collection variable value.

![image](https://user-images.githubusercontent.com/5332516/107359488-66350700-6add-11eb-8ced-0082b8c6bec7.png)

![image](https://user-images.githubusercontent.com/5332516/107359549-79e06d80-6add-11eb-8027-3d46615caa36.png)
