### ISSUE TITLE
y-axis scaling when there is no data

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#165]
On the "week" view for https://dashtweak.com/dashboards/144, we don't have any visible data for humidity, yet the scale is automatically set to a max higher than 80.

![image](https://user-images.githubusercontent.com/784273/90646600-ae165800-e237-11ea-8484-f23577d11521.png)

If you look at the data returned, you will see why:

![image](https://user-images.githubusercontent.com/784273/90646972-1a915700-e238-11ea-8ea2-45238a094e26.png)

Notice that we do have values for humidity in the result above, but they don't appear on the chart. If they are ignored on the chart, they should not be used when scaling the y-axis either.

**Comment by rochecompaan** [comment]
@GronumSmith, for your reference.

**Comment by nvernooy** [comment]
Exclude results from charts that have only one record

![image](https://user-images.githubusercontent.com/5332516/90761162-4c132c80-e2e3-11ea-86d4-226f2a26cab6.png)

![image](https://user-images.githubusercontent.com/5332516/90761207-5d5c3900-e2e3-11ea-8517-c7d8c4693192.png)
