### ISSUE TITLE
Improve Layout (space utilization) for Landscape on Mobile

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#167]
See also with Issues #98 and #99 
There is quite a lot of unnecessary spaces when viewed in Landscape (play with the images to see what happens when headers scroll up/down/away)
![image](https://user-images.githubusercontent.com/35992133/90653398-6abfe780-e23f-11ea-9553-5fd49f1da985.png)

It does look better on Portrait view, but please assess. 
![image](https://user-images.githubusercontent.com/35992133/90653510-8f1bc400-e23f-11ea-8503-75f978a7a7b4.png)

**Comment by GronumSmith** [comment]
There seems to be a lot of open space between different charts.  Can be made less. 
Again in the light of making a bit more compact - if one made the legend and values smaller the charts will be closer to each other and relation between charts will be easier to see. 

![image](https://user-images.githubusercontent.com/35992133/90757053-677b3900-e2dd-11ea-87b3-dc68a9cbc155.png)

**Comment by nvernooy** [comment]
Use a smaller font size for the date selector on mobile 
![image](https://user-images.githubusercontent.com/5332516/100757592-3986b400-33f7-11eb-8e99-f3acf2464bf0.png)


Use less padding and display with row layout in landscape view
![image](https://user-images.githubusercontent.com/5332516/100757484-18be5e80-33f7-11eb-96a9-380f85c50692.png)


Use less spacing between charts and make legends more compact
![image](https://user-images.githubusercontent.com/5332516/100757334-ec0a4700-33f6-11eb-815c-c863c842f85a.png)
![image](https://user-images.githubusercontent.com/5332516/100758428-2d4f2680-33f8-11eb-9311-4becd851f256.png)

**Comment by GronumSmith** [comment]
Thanks Neil, smaller font makes a big difference I think!
What about removing some of the space above and below the header? 
![image](https://user-images.githubusercontent.com/35992133/100761288-663cca80-33fb-11eb-8e13-f11c981db789.png)

**Comment by nvernooy** [comment]
Less space on the navbar

![image](https://user-images.githubusercontent.com/5332516/100847131-135d2480-3488-11eb-8bb2-2d6a3ff40c19.png)
