### ISSUE TITLE
Slider disconnected between Charts: Reconnect

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#168]
As far as I remember ? the sliders on different charts was connected i.e. when sliding it slides on all charts and reads data off all. 
This is necessary because one would like to e.g. see relationship between charts or for a certain day/time see values of different parameters. 
At the moment it seems as if they are no longer connected. 

![image](https://user-images.githubusercontent.com/35992133/90756854-2125da00-e2dd-11ea-802e-91b48fe5c835.png)

**Comment by rochecompaan** [comment]
If you tap, it updates on all charts. If you swipe, it disconnects. Should be easy to fix.
