### ISSUE TITLE
Legend on Bar Chart cut off by chart below

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#169]
Legend on Bar Chart cut off by chart below
This seems to be only with Bar Chart? 
on 
https://dashtweak.com/dashboards/30 

![image](https://user-images.githubusercontent.com/35992133/90757186-9c878b80-e2dd-11ea-9af3-c1f199f9b32f.png)

**Comment by nvernooy** [comment]
Calculate legend row heights

![image](https://user-images.githubusercontent.com/5332516/90794406-0ec39480-e30d-11ea-917a-a01e18ff2164.png)
