### ISSUE TITLE
Multiple data sources should be supported in Charts

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#170]
We are now able to do multiple queries, separated by semi-colon. 
But the EditChart widget allows the selection of only 1 Data Source (from the dropdown list)
![image](https://user-images.githubusercontent.com/35992133/90893553-7c2ffd80-e3bf-11ea-93a9-ae2dbd19990c.png)
It should ideally be possible to select multiple data sources (or set this elsewhere? 
Note the FROM allows the specification of the source.  so why is it then necessary to have the selection of same? data source in the dropdown.. It seems as if query FROM value needs to correlate with the Data Source selected. 
Can one not set All Data Sources in a more global setting and then queries can be made to any of these ?  
An example application is where we would like to plot the **measured** data from "izintorain" and **predicted** from "izinto forecasts", or eg measured and aggregations on same chart ?? 

OK security an issue ? might only be "now" because IZINTO and MyCity are using same DT instance.

**Comment by rochecompaan** [comment]
One can add multiple queries to a dashboard, closing issue.
