### ISSUE TITLE
Time format (in Tables) but possibly else as well

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#172]
In the interest of compactness (especially for mobile) I would like to suggest that we use 24:00 format instead of AM/PM.  
![image](https://user-images.githubusercontent.com/35992133/91989586-f69e3d00-ed30-11ea-93b6-529f6832bf40.png)

**Comment by rochecompaan** [comment]
@GronumSmith modify the date formatting in your script to include `hour12: false`, eg:

```
                    if (dateSelection.view === 'Hour' || dateSelection.view === 'Day') {
                        return date.toLocaleString('en-US', {hour: 'numeric', minute: '2-digit', hour12: false});
```
