### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#173]
Add a "Queries" menu item below "Data Source" on the "Settings" menu (gear icon).

Add a new Query model to Pyramid and allow any user to add queries through a UserQuery mapping table. 

A query should have the following properties:

- *Name* (This refers to the name of the query, eg weather_forecast_data. This must be unique across al the user's queries. Add a composite key on user_id and query name) 
- *Query* (The query string), eg:
```
SELECT mean("temperature") AS "Temperature", mean("wind") AS "Wind speed", mean("windDirection") AS "Wind Direction", mean("humidity") AS "Humidity" FROM "izintorain"."autogen"."measurement" WHERE
         ("dev_id" = ${dev_id}) AND ${range} GROUP BY time(${group_by}), "dev_id" fill(none)
```
- *DataSource* (a reference to Data Source)

Update the Dashboard iFrame Message protocol to only allow queries using the following syntax:
```
let query = {
    name: 'weather_forecast_data',
    values: {dev_id:  '12345', range: dateSelection.dateRange, group_by: group_by}
}
```

Finally, and very important, only assemble the query on the Pyramid server before dispatching it to the data source to prevent malicious users to write open-ended queries to query sensitive data.

Simplify the route to execute a query by simply calling `/queries/<query_id>/run`. Use POST to submit parameters defined as `values` in the script sample above.

@jpm-izinto are you happy with the above?

**Comment by jpm-izinto** [comment]
Yes I mostly agree with this.

Just one thing:
> and allow any user to add queries through a UserQuery mapping table.

Shouldn't this read as "all admin users to add queries"?
And shouldn't the query be linked to the dashboard, rather than to the user? ie DashboardQuery mapping table rather than UserQuery.

**Comment by rochecompaan** [comment]
I would like to allow any user to add collections, dashboards, data sources and queries to DashTweak where it is essentially private to that user until it is published or shared. I understand that you might not want that for a weather station dashboard but that can easily be made configurable. And maybe you do want to allow your own users to build their own dashboards over time - it would be very empowering!

For this reason, the mapping is between the User and the Query. I think one should be able to use Queries on multiple dashboards. If you make it dashboard specific, you might repeat the same query 20 times.

**Comment by rochecompaan** [comment]
@nvernooy I use the following query in my script:
```
    function loadQuery() {
        var query_group_by = GroupBy[dateSelection['view']]; 
        var query = {
            'query':
                {
                    'name': 'table_query',
                    'values': {dev_id: '1406300003', range: dateSelection.dateRange, query_group_by: query_group_by}
                }
        };
        console.log(query);
        window.top.postMessage(query, '*');
    }
```

I created a `table_query` using the following `query_string`:
```
SELECT mean("temperature") AS "Temperature", mean("wind") AS "Wind speed", mean("windDirection") AS "Wind Direction", mean("humidity") AS "Humidity" FROM "izintorain"."autogen"."measurement" WHERE
             ("dev_id" = '${dev_id}') AND ${range} GROUP BY time(${query_group_by}), "dev_id" fill(none)
```

This gives me a Bad Request error: error parsing query. What is wrong?
