### ISSUE TITLE
Tables: Padding of cells - Reduce 

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#176]
It seems as if there is unnecessary padding around the cells of tables. 
It is is the css at lower level than where I have access. I have created a table where the Fields/ "Header Titles" are a single character, one would preferably want a unit next to each value, but in some cases one might drop it e.g. if all values in a table are of same  type (mm) or deg
For now I would like to suggest that one reduces the padding: 
See https://dashtweak.com/dashboards/170 on mobile 
![image](https://user-images.githubusercontent.com/35992133/92210474-0cc20f80-ee8f-11ea-8c42-2d64c60733a1.png)

**Comment by rochecompaan** [comment]
@GronumSmith you can do any CSS styling in the script:

![image](https://user-images.githubusercontent.com/784273/92222809-d771ed80-ee9f-11ea-9491-d0b94bf16e5f.png)

For more info on padding, see https://developer.mozilla.org/en-US/docs/Web/CSS/padding
