### ISSUE TITLE
Y-axis values cut off on left

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#177]
https://dashtweak.com/dashboards/23
Value should be 1.200   "1200"
![image](https://user-images.githubusercontent.com/35992133/92398646-4746d900-f129-11ea-9b85-2dbc587e14cf.png)

**Comment by GronumSmith** [comment]
Of course it is difficult because one would like all charts to be aligned on left, and making provision for X decimals will push graph to the right leaving too much space.
Should one not switch from : e.g. 1200 and 1000 above to 1.2k 1.0k   or 1.2 and 1.0 with "x1000" "x10^3" below the values.

**Comment by nvernooy** [comment]
Format long numbers

![image](https://user-images.githubusercontent.com/5332516/100427514-3ad47b80-309b-11eb-9848-dad419c23c01.png)

**Comment by GronumSmith** [comment]
This seems to work nice! with the k for (x1000) the problem is with rain where the correct value should be 
0.2mm (in this case) it is listed as 200m (200 milli) which is correct but it could EASILY be read as 200m(eter).  Not sure how to fix... and be general.
https://dashtweak.com/dashboards/280/view 
![image](https://user-images.githubusercontent.com/35992133/100620682-5eabf180-3327-11eb-8629-25facba16ac5.png)

**Comment by nvernooy** [comment]
We rather removed formatting the numbers and instead increase the margin on the chart depending on the size of the max value

![image](https://user-images.githubusercontent.com/5332516/107501567-3dc21100-6ba0-11eb-951e-8f8472096a93.png)

![image](https://user-images.githubusercontent.com/5332516/107501357-f50a5800-6b9f-11eb-8594-19190cfe8b1a.png)
