### ISSUE TITLE
Link queries to dashboard

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#179]
It seems that having all a user's queries in one place might quickly become unwieldy.

Please refactor queries to be dashboard specific, similar to variables. 

Ensure that the route to a query is relative to a dashboard eg. `/dashboards/123/queries/weather_table_data`

The name of the query only has to be unique in the context of a dashboard, no longer across all queries for a given user.

Anybody that has access to the dashboard must be able to run the query. 

Please add unit tests to test the above scenarios.

**Comment by GronumSmith** [comment]
Sounds like a really good/better way of doing things!
