### ISSUE TITLE
Dashboard UI

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#181]
Proposed dashboard UI:

o-> Dashboard View
    
    +-----------------------------------------------------------------------------------------------------------------------+
    |                                                                                                                       |
    |    DashTweak                                                                               [ Account ] [ Settings ]   |
    |                                                                                                                       |
    +-----------------------------------------------------------------------------------------------------------------------+
    |                                                                                                                       |
    |                                                                                                                       |
    |    My Collection > My Dashboard                                         _ View _  [ Edit ] [ Queries ]  [ Variables ] |
    |                                                                                                                       |
    |                                                                                                                       |
    |        E +-------------------------*--+     E |                         o                                             |
    |        D |-------------------*--*--|--*     D |                   o  o  |  o                                          |
    |        C |-------------*--*  |  |  |  |     C |             o  o  |  |  |  |                                          |
    |        B |-------*--*  |  |  |  |  |  |     B |       o  o  |  |  |  |  |  |                                          |
    |        A +-*--*--+--+--+--+--+--+--+--+     A +-o--o--|--|--|--|--|--|--|--|                                          |
    |            5 10 15 20 25 30 35 40 45 50         5 10 15 20 25 30 35 40 45 50                                          |
    |                                                                                                                       |
    |                                                                                                                       |
    |    85.67 ¦                                       ??                                                                   |   
    |    78.20 ¦                                       ¦¦                  ??                                               |
    |    70.73 ¦                                       ¦¦  ?? ?? ??   ??  ???-?                                             | 
    |    63.27 ¦                        ??         ?-? ¦¦ ????¦?-?????¦?--?   ¦?                                            |                                              
    |    55.80 ¦   ??                 ??¦¦?? ????  ¦ ?-??-?  ¦¦    ¦¦¦¦       ??                                            |     
    |    48.33 ¦   ¦??      ?--?      ¦¦¦¦¦??¦??¦  ¦         ??    ????                                                     |         
    |    40.87 ¦?? ¦ ????  ??  ?-????-????? ??  ?--?                                                                        |
    |    33.40 ¦¦¦ ¦  ??????     ¦¦??                                                                                       |   
    |    25.93 ¦¦¦??     ??      ??                                                                                         |  
    |    18.47 +?¦¦                                                                                                         |          
    |    11.00 ¦ ??                                                                                                         |   
    |          +----------------------------------------------------------------                                            |       
    |        2011        2012        2013        2014        2015        2016                                               |    
    |                                                                                                                       |
    |                                                                                                                       |
    +-----------------------------------------------------------------------------------------------------------------------+

o-> Dashboard Edit
    
    +-----------------------------------------------------------------------------------------------------------------------+
    |                                                                                                                       |
    |    DashTweak                                                                               [ Account ] [ Settings ]   |
    |                                                                                                                       |
    +-----------------------------------------------------------------------------------------------------------------------+
    |                                                                                                                       |
    |                                                                                                                       |
    |    My Collection > My Dashboard                                         [ View ]  _ Edit _ [ Queries ]  [ Variables ] |
    |                                                                                                                       |
    |       +-----------------------------------------------------------------------------------------------------+         |
    |    1  |  <html>                                                                                             |         |
    |    2  |    <head></head>                                                                                    |         |
    |    3  |    <body>                                                                                           |         |
    |    4  |       <script>                                                                                      |         |
    |    5  |       console.log("Hello world!")                                                                   |         |
    |    6  |       </script>                                                                                     |         |
    |    7  |    </body>                                                                                          |         |
    |    8  |  </html>                                                                                            |         |
    |    9  |                                                                                                     |         |
    |    10 |                                                                                                     |         |
    |    11 |                                                                                                     |         |
    |    12 |                                                                                                     |         |
    |    13 |                                                                                                     |         |
    |    14 |                                                                                                     |         |
    |    15 |                                                                                                     |         |
    |    16 |                                                                                                     |         |
    |    17 |                                                                                                     |         |
    |    18 |                                                                                                     |         |
    |    19 |                                                                                                     |         |
    |    20 |                                                                                                     |         |
    |    21 |                                                                                                     |         |
    |    22 |                                                                                                     |         |
    |    23 |                                                                                                     |         |
    |       +-----------------------------------------------------------------------------------------------------+         |
    |                                                                                                                       |
    |    +----------+                                                                                                       |
    |    |   Save   |                                                                                                       |
    |    +----------+                                                                                                       |
    |                                                                                                                       |
    +-----------------------------------------------------------------------------------------------------------------------+

o-> Dashboard Queries
    
    +-----------------------------------------------------------------------------------------------------------------------+
    |                                                                                                                       |
    |    DashTweak                                                                               [ Account ] [ Settings ]   |
    |                                                                                                                       |
    +-----------------------------------------------------------------------------------------------------------------------+
    |                                                                                                                       |
    |                                                                                                                       |
    |    My Collection > My Dashboard                                         [ View ]  [ Edit ] _ Queries _  [ Variables ] |
    |                                                                                                                       |
    |    Write queries to access data in your dashboard scripts.                                                            | 
    |                                                                                                                       |
    |    Add your first query.                                                                                              |
    |                                                                                                                       |
    |    .------------------.                                                                                               |
    |    | + Add Query  {b} |                                                                                               |
    |    '------------------'                                                                                               |
    |                                                                                                                       |
    |                                                                                                                       |
    +-----------------------------------------------------------------------------------------------------------------------+

o-> Dashboard: Add query
    
    +-----------------------------------------------------------------------------------------------------------------------+
    |                                                                                                                       |
    |    DashTweak                                                                               [ Account ] [ Settings ]   |
    |                                                                                                                       |
    +-----------------------------------------------------------------------------------------------------------------------+
    |                                                                                                                       |
    |                                                                                                                       |
    |    My Collection > My Dashboard                                         [ View ]  [ Edit ] _ Queries _  [ Variables ] |
    |                                                                                                                       |
    |                                                                                                                       |
    |    Write queries to access data in your dashboard scripts.                                                            | 
    |                                                                                                                       |
    |    Add your first query.                                                                                              |
    |                                  .--------------------------------------------------------------------------.         |
    |    .------------------.          |  {em}                                                                    |         |
    |    | + Add Query  {b} |          |  Query name                                                              |         |
    |    '------------------'          |  * no spaces or special characters allowed - must be usable as JS var    |         |
    |          |                       |  +-------------------------------------------------------------------+   |         |
    |          +---------------------> |  | weather_table_data                                                |   |         |
    |                                  |  +-------------------------------------------------------------------+   |         |
    |                                  |                                                                          |         |
    |                                  |  Query string                                                            |         |
    |                                  |  +-------------------------------------------------------------------+   |         | 
    |                                  |  | select temp from measurements where dev_id = ${dev_id}            |   |         |
    |                                  |  +-------------------------------------------------------------------+   |         |
    |                                  |                                                                          |         |
    |                                  |  Data Source                                                             |         |
    |                                  |  +-------------------------------------------------------------------+   |         |
    |                                  |  | izintorain                                                     |v |   |         |
    |                                  |  +-------------------------------------------------------------------+   |         |
    |                                  |                                                                          |         |
    |                                  |  Test data                                                               |         |
    |                                  |  +-------------------------------------------------------+ +---------+   |         |
    |                                  |  | {dev_id: 12345}                                       | | Test    |   |         |
    |                                  |  +-------------------------------------------------------+ +---------+   |         |
    |                                  |                                                                          |         |
    |                                  |  Test result                                                             |         |
    |                                  |  +-------------------------------------------------------------------+   |         |
    |                                  |  |{"results":[                                                       |   |         |
    |                                  |  |  {"statement_id":0,"series":[                                     |   |         |
    |                                  |  | {"name":"measurement","columns":["time","difference"], "values":[ |   |         |
    |                                  |  | ["2020-08-31T00:00:00Z",2418.346649484709],                       |   |         |
    |                                  |  | ["2020-09-01T00:00:00Z",4748.4536082474515]                       |   |         |
    |                                  |  |     ]]}]}]}                                                       |   |         |
    |                                  |  |                                                                   |   |         |
    |                                  |  +-------------------------------------------------------------------+   |         |
    |                                  |                                                                          |         |
    |                                  |  +------------+  +------------+                                          |         |
    |                                  |  |  Submit {b}|  |  Cancel {b}|   * don't allow submit if query fails    |         |
    |                                  |  +------------+  +------------+                                          |         |
    |                                  |                                                                          |         |
    |                                  '--------------------------------------------------------------------------'         |
    |                                                                                                                       |
    |                                                                                                                       |
    +-----------------------------------------------------------------------------------------------------------------------+

o-> Dashboard: List queries
    
    +-----------------------------------------------------------------------------------------------------------------------+
    |                                                                                                                       |
    |    DashTweak                                                                               [ Account ] [ Settings ]   |
    |                                                                                                                       |
    +-----------------------------------------------------------------------------------------------------------------------+
    |                                                                                                                       |
    |                                                                                                                       |
    |    My Collection > My Dashboard                                         [ View ]  [ Edit ] _ Queries _  [ Variables ] |
    |                                                                                                                       |
    |                                                                                                                       |
    |                                                                                                                       |
    |    weather_table_data             [ edit ] [ delete ]  <- on hover                                                    |
    |                                                                                                                       |
    |    flow_rate_data                                                                                                     |
    |                                                                                                                       |
    |                                                                                                                       |
    +-----------------------------------------------------------------------------------------------------------------------+

**Comment by nvernooy** [comment]
Updated dashboard UI to edit script and queries in separate tabs

![image](https://user-images.githubusercontent.com/5332516/92578021-99077480-f28b-11ea-90bb-781e66c05058.png)
![image](https://user-images.githubusercontent.com/5332516/92578122-bf2d1480-f28b-11ea-9082-a7e7e862e958.png)

**Comment by nvernooy** [comment]
Add test query function

![image](https://user-images.githubusercontent.com/5332516/92942019-6018fc80-f451-11ea-8153-3ec30b7aa5e2.png)

![image](https://user-images.githubusercontent.com/5332516/92941949-4a0b3c00-f451-11ea-963b-520741480db3.png)
