### ISSUE TITLE
Copy the Queries associated with a Dashboard WITH Copy of Dashboard

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#182]
When copying a dashboard the queries associated with that dashboard are not copied. 
They should be copied WITH. 

My understanding of hierarchy is
- Collection
 - Dashboard (has Queries which apply to that dashboard)
  - Widget (Panel is term used in Grafana)

How would Queries associated with Panel (SingleStat and Chart) as currently done fit in the hierarchy?

Also for scaling/extending it should be possible to copy a Collection retaining all Dashboards, Panels and Queries which underlie that Collection.

**Comment by nvernooy** [comment]
Queries are copied with a dashboard as well as with the dashboards in a collection.

**Comment by GronumSmith** [comment]
Thanks Niel, just a check... I did not specify in particular .. but this copy of queries is not happening with "Scripts"

**Comment by rochecompaan** [comment]
@GronumSmith queries are copied for scripts now. See https://dashtweak.com/dashboards/189
