### ISSUE TITLE
Parent container does not expand to full height of iframe

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#183]
The container for the iframe must expand to the full height of the iframe, currently it doesn't and it causes a double scroll bar. Refer to #155 for some links on the topic. The first link is to an issue with detail on how to implement it with Angular. If you can find a solution without using the iframe-resizer that would be great but I suspect you will need it.

Notice how we have 2 scrollbars in the screenshots below:
![image](https://user-images.githubusercontent.com/784273/93458561-be762d00-f8e0-11ea-85bb-096d98016ac4.png)

**Comment by nvernooy** [comment]
Fit the iframe to the content area and overflow properly

![image](https://user-images.githubusercontent.com/5332516/93573109-08b9e580-f997-11ea-9833-7307d6085a3d.png)
![image](https://user-images.githubusercontent.com/5332516/93573438-6bab7c80-f997-11ea-9f77-11fbe2bf3ea1.png)

**Comment by rochecompaan** [comment]
The fix in #189 caused regression and is breaking the parent container height. The iframe is scrolling instead of the parent window. See below:

![image](https://user-images.githubusercontent.com/784273/94787022-05c8e700-03d2-11eb-9ea8-03778f5db7bf.png)

![image](https://user-images.githubusercontent.com/784273/94786974-f0ec5380-03d1-11eb-80ac-0c00803815ca.png)
