### ISSUE TITLE
Table with multiple queries

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#184]
Please develop a table that retrieves temperature data from the forecasts and izintorain databases and compare the values between the selected and forecast for the given date range.
```
+--------------------------------------------------+
| Date                     |  Actual  |   Forecast |
+--------------------------------------------------+
| 10 September             |  15 °C   |   12 °C    |
| 10 September             |  16 °C   |   15 °C    |
| 10 September             |  18 °C   |   18 °C    |
| 10 September             |  11 °C   |   13 °C    |
| 10 September             |  19 °C   |   13 °C    |
+--------------------------------------------------+
```

An example temperature query from the forecast db:
```
SELECT "temperature" FROM (SELECT last("temperature") AS "temperature" FROM "forecasts"."autogen"."forecast_corrected" WHERE ("installation_id" = '21.0' AND "forecast_service" = 'darksky') AND $timeFilter GROUP BY "forecast_age")
```

**Comment by rochecompaan** [comment]
@GronumSmith and @jpm-izinto please let us know if this is what you had in mind.

**Comment by GronumSmith** [comment]
Yes thanks Roche:  If I see how it is done once I can modify and do similar other parameters 
A more advanced challenge would be 
+---------------------------------------------+
| Installation   |  Mountain  |   River    |   Store   |
+---------------------------------------------+
| Jul               |  15 mm      |   14mm  |   24mm |
| Aug             |    5 mm      |     4mm  |     3mm |
| Sep              |  12 mm      |   24mm  |   23mm |
+---------------------------------------------+
Not sure if this will be possible the Titles Installation Names.

**Comment by rochecompaan** [comment]
@GronumSmith, that can also be done but I don't see how that would be an example of multiple queries? Is it related to this issue or is it another table you have in mind?

**Comment by GronumSmith** [comment]
This is what I briefly described i.e. different installations in columns and different time in rows. 
Multiple queries from different Installations, but yes not different databases (as your example)
For clarity: Lets do in two steps/fases?
1) Your example where multiple (2) data sources are queried
2) My example where same data source is queried but querying different installations (could probably be done with site_id="A" OR site_id="B"

**Comment by rochecompaan** [comment]
Querying multiple installations can be done in one query.

**Comment by nvernooy** [comment]
Added a table showing a measurement across installations in a single site
https://dashtweak.com/dashboards/183

![image](https://user-images.githubusercontent.com/5332516/93622645-c667c700-f9dd-11ea-915f-299cf2f992fa.png)

**Comment by GronumSmith** [comment]
AWESOME!
