### ISSUE TITLE
Edit (to hide?) some Pins on GIS Map

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#186]
Although we aim to have DT mainly for full weather stations we also have other types of sensors at different installations. 
e.g. Soil Moisture Sensors (with multi level sensors, e.g. 4 to 6 sensors at different heights)
and also Solar Radiation
One of the most obvious examples for now/here is to be able to hide certain Installations from the GIS Map e.g. Soil Moisture here 
https://dashtweak.com/dashboards/185
![image](https://user-images.githubusercontent.com/35992133/93996403-82384600-fd92-11ea-9514-ae3b2e1e515d.png)

Please also note:  Ideally one should be specify per Installation which parameters should be displayed -> query per installation??? that can maybe override a dashboard query as is currently done? 
But it gets complex discuss in issue

**Comment by rochecompaan** [comment]
@GronumSmith you can limit the number of installations visible on the map by modifying your query. Similarly, you can customise the parameters you want to display on the map by modifying the query. I don't think @jpm-izinto should have any issue doing this, but let him look at the current script and confirm.

**Comment by rochecompaan** [comment]
Can we close this issue?

**Comment by GronumSmith** [comment]
Yes probably possible with correct query.
