### ISSUE TITLE
Update / Change Wind arrows to EricFlowers 

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#188]
If the icons to be used will be 
https://erikflowers.github.io/weather-icons/ 
I would like to suggest that we use the same (at least arrow and/or colour) 
![image](https://user-images.githubusercontent.com/35992133/94003723-ed3a4a80-fd9b-11ea-87d2-e4026fdff3f8.png)

**Comment by nvernooy** [comment]
Change wind arrows in chart and table to arrow icons

![image](https://user-images.githubusercontent.com/5332516/94531280-a1c0ea00-023c-11eb-98cb-335bae14cb36.png)
![image](https://user-images.githubusercontent.com/5332516/94531354-c0bf7c00-023c-11eb-902a-76ff651736c2.png)

**Comment by rochecompaan** [comment]
@GronumSmith are you have with the use of Eric's icons? Can we close this issue?
