### ISSUE TITLE
Top menu bar disappears

### ISSUE THREAD

**Issue by jpm-izinto** [upfrontsystems/izinto-angular#189]
When scrolling down on a dashboard the top menu bar disappears, as is a feature.

But, when I scroll back up the menu does not appear again. Even browsing to a different page, and even pressing the browser's back button does not make the menu bar show up again. A full refresh of dashtweak is necessary to make the menu bar show up again.

![Screenshot from 2020-09-28 11-29-15](https://user-images.githubusercontent.com/54270670/94415474-dd48af00-017d-11eb-8dfe-6f719815f6ed.png)

**Comment by rochecompaan** [comment]
@jpm-izinto what browser and OS are you using?

**Comment by jpm-izinto** [comment]
Google Chrome on Ubuntu.

Maybe this is related to the two scroll bars on the right?

**Comment by jpm-izinto** [comment]
Also when I scroll all the way down I can scroll past the canvas.

![Screenshot from 2020-09-28 11-56-23](https://user-images.githubusercontent.com/54270670/94418402-a83e5b80-0181-11eb-82a7-668adaf1f409.png)

**Comment by jpm-izinto** [comment]
I also see this error in the developer console, which might be related:
```
polyfills-es2015.acf10cc8d05fe0bad1af.js:1 Uncaught TypeError: Cannot read property 'getElementRef' of undefined
    at a.project (main-es2015.0e5fb62b934d2b7a27e6.js:1)
    at a._next (main-es2015.0e5fb62b934d2b7a27e6.js:1)
    at a.next (main-es2015.0e5fb62b934d2b7a27e6.js:1)
    at o.clearThrottle (main-es2015.0e5fb62b934d2b7a27e6.js:1)
    at o.notifyNext (main-es2015.0e5fb62b934d2b7a27e6.js:1)
    at r._next (main-es2015.0e5fb62b934d2b7a27e6.js:1)
    at r.next (main-es2015.0e5fb62b934d2b7a27e6.js:1)
    at s.l (main-es2015.0e5fb62b934d2b7a27e6.js:1)
    at s._execute (main-es2015.0e5fb62b934d2b7a27e6.js:1)
    at s.execute (main-es2015.0e5fb62b934d2b7a27e6.js:1)
```

**Comment by rochecompaan** [comment]
Yes, the two scrollbars are most certainly causing this. I actually don't see the point of hiding the top menu bar on the desktop, we should limit this to mobile.

**Comment by rochecompaan** [comment]
@jpm-izinto can you test to see if this is resolved for you? You might have to reload the page a few times to ensure you have the latest version.

**Comment by jpm-izinto** [comment]
Still happening on the root page. Can't reproduce the menu bar issue on a dashboard page though.

Double scrollbar and overscroll at end is still there. So is the error in the console.

![Screenshot from 2020-10-02 11-34-58](https://user-images.githubusercontent.com/54270670/94909372-5c522600-04a3-11eb-8ab3-7cb34ab6f773.png)

**Comment by rochecompaan** [comment]
If you inspect, what is height set too on mat-sidenav-content?

![image](https://user-images.githubusercontent.com/784273/94926922-d4c7df80-04c1-11eb-9f25-18444cc51a69.png)

**Comment by jpm-izinto** [comment]
![image](https://user-images.githubusercontent.com/54270670/95049730-a24cfb00-06ea-11eb-9889-35fb6b405353.png)

but when I start scrolling down, this value gets updated to the following

![image](https://user-images.githubusercontent.com/54270670/95049829-d0cad600-06ea-11eb-86a2-f07653dcdf58.png)

**Comment by rochecompaan** [comment]
@nvernooy do you have an Ubuntu VM to test this on?

**Comment by nvernooy** [comment]
@rochecompaan yes I have a vm, just need to start up dashtweak on it

**Comment by rochecompaan** [comment]
@nvernooy I don't think it is necessary to install DashTweak, just see if you can reproduce and debug the CSS issue. You should be able to fix the CSS in Inspect and then you can simply add the fix to our CSS.

**Comment by nvernooy** [comment]
@jpm-izinto I tested this on Chrome and Firefox on Ubuntu, my versions are a bit out of date but I was not able to reproduce the problem

![image](https://user-images.githubusercontent.com/5332516/95183710-a3ebf100-07c6-11eb-83f8-5604a4ac0294.png)
![image](https://user-images.githubusercontent.com/5332516/95183876-e31a4200-07c6-11eb-92d4-10f804188bc9.png)

I'm using Chrome Version 76.0.3809.100 on Ubuntu 16.04.
Maybe it's possible the card layout update resolved this issue?

**Comment by nvernooy** [comment]
@jpm-izinto I tested this on Chrome and Firefox on Ubuntu, my versions are a bit out of date but I was not able to reproduce the problem

![image](https://user-images.githubusercontent.com/5332516/95183710-a3ebf100-07c6-11eb-83f8-5604a4ac0294.png)
![image](https://user-images.githubusercontent.com/5332516/95183876-e31a4200-07c6-11eb-92d4-10f804188bc9.png)

I'm using Chrome Version 76.0.3809.100 on Ubuntu 16.04.
Maybe it's possible the card layout update resolved this issue?

**Comment by jpm-izinto** [comment]
Maybe try a newer Ubuntu. A lot changed since 16.04, and the latest is also an LTS: 20.04.
Chrome version: Version 85.0.4183.121 (Official Build) (64-bit)

With the card layout the menu bar still disappears, the canvas still overscrolls at the end, and I still see the error in the developer console:

![Screenshot from 2020-10-06 11-33-58](https://user-images.githubusercontent.com/54270670/95184899-4a84c180-07c8-11eb-8ba1-057bd076962d.png)
![Screenshot from 2020-10-06 11-33-33](https://user-images.githubusercontent.com/54270670/95184904-4c4e8500-07c8-11eb-9152-df73d68e6d6e.png)
![Screenshot from 2020-10-06 11-34-34](https://user-images.githubusercontent.com/54270670/95184891-4789d100-07c8-11eb-8d6e-28b1c149ac54.png)


![image](https://user-images.githubusercontent.com/54270670/95184721-101b2480-07c8-11eb-98af-1b7a73039c02.png)

**Comment by nvernooy** [comment]
@jpm-izinto I've tested the website on a new install of Ubuntu 20.4 and Chrome 85, I was still not able to reproduce your error.
Could you test if the same error appears on Firefox, and try clearing your cache?

**Comment by jpm-izinto** [comment]
Firefox: work correctly
Chrome incognito: works correctly
Chrome with a different user logged in: works correctly
Chrome with main user after clearing all site data: issue still there

I was very surprised by this result, and confused why my Izinto user's chrome had this issue. I removed all chrome extensions and now it is working correctly. So one of them must have caused this.

We can close this issue for now.

**Comment by rochecompaan** [comment]
Thanks, @jpm-izinto. Extensions can very easily cause CSS aberrations ...
