### ISSUE TITLE
Weather forecast icon and description

### ISSUE THREAD

**Issue by jpm-izinto** [upfrontsystems/izinto-angular#191]
We have created an example Grafana table that shows the icon name and the forecast text in a table:
https://grafana.izinto.cloud/d/18GQgpFMk/icons-and-desc?orgId=1

This is a good example query to use for a forecast table in Dashtweak.

**Comment by rochecompaan** [comment]
@jpm-izinto can you please paste the query as a comment on this issue. I don't seem to have access to the dashboard and @nvernooy doesn't have access to your Grafana dashboard either.

**Comment by rochecompaan** [comment]
@nvernooy here is the query:
```
SELECT "icon", "description" FROM "forecast_corrected" WHERE ("forecast_service" = 'yr.no') AND $timeFilter tz('UTC')
```

**Comment by nvernooy** [comment]
Add the icons and description to the forecast table

![image](https://user-images.githubusercontent.com/5332516/94579632-5678fc80-0279-11eb-966f-c08ba70cbb18.png)

**Comment by rochecompaan** [comment]
@GronumSmith are you happy with the way the icon and description are shown?

@nvernooy can we adapt the forecast example to use a similar column definition as in #190

**Comment by GronumSmith** [comment]
link to example where this was done ?

**Comment by rochecompaan** [comment]
https://dashtweak.com/dashboards/182
