### ISSUE TITLE
GIS Map: allow Satellite View i.e. toggle between layers

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#193]
It is sometimes very helpful to make sure/confirm that an installations position is correctly represented, especially where there are no roads or markings that appear on a "standard" style. 
It would be great to allow this toggle in a similar way /very accessible way as is done with the different parameters (temp/humidity) is currently done, maybe bottom right corner? 

{Does Leaflet use Mapbox? seems like that from the Queries?}

**Comment by rochecompaan** [comment]
@GronumSmith, unless @jpm-izinto knows how to do this easily, Leaflet doesn't seem to support the Satellite layer out of the box. 

According to this SO post, one can use Google's Satellite layer or you have to use a plugin alternatively.
https://stackoverflow.com/questions/9394190/leaflet-map-api-with-google-satellite-layer

I feel this is out of scope for the current iteration. Can we defer this to a future release?

**Comment by jpm-izinto** [comment]
I've updated the map to have a background layer chooser.

List of available background layers is available here:
https://leaflet-extras.github.io/leaflet-providers/preview/
