### ISSUE TITLE
GIS: Better font on the pin, popup font seems OK

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#194]
The font used to display text and values on the Pins' does not render very well. 
Suggest that we find a better default. 
Might be best if same font as used else where in DT is used, also for the popup.
This is on PC/Firefox
![image](https://user-images.githubusercontent.com/35992133/94559794-09d5f700-0262-11eb-83b2-b095cd919036.png)

But on Mobile Android it actually looks very nice !
![image](https://user-images.githubusercontent.com/35992133/94560343-ccbe3480-0262-11eb-849d-fcbd936b6711.png)

**Comment by nvernooy** [comment]
Use the default browser font on the pins

![image](https://user-images.githubusercontent.com/5332516/94573359-4e698e80-0272-11eb-979e-cec3161df79b.png)

**Comment by rochecompaan** [comment]
@GronumSmith are you happy with the font now? Can we close this issue?
