### ISSUE TITLE
GIS Map: Minimise after selection ? or find a way for it not to dominate the screen (especially on Mobile)

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#196]
Test on: https://dashtweak.com/dashboards/162
The parameter selection panel remains and dominates the view, especially on Mobile (on PC it does not matter as much (in fact there it is nice easy to select
1) Can we do it in a different / smaller way ?  maybe use only clear Icons and radio buttons.  Or for a little more clarity the parameter Unit. This approach will leave a long "thin" vertical bar on the right
2) or similar approach as Hamburger Menu used for different Map Layer options 
![image](https://user-images.githubusercontent.com/35992133/94678872-7d8a0980-031f-11eb-9828-a6eb18472ecb.png)

**Comment by nvernooy** [comment]
#198 remove the measurements panel and only display temperate and the sky icon on the map
