### ISSUE TITLE
Map measurement selection on mobile takes up to much space

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#198]
The measurement selection on a mobile screen expands to the full height of the screen:

![image](https://user-images.githubusercontent.com/784273/94683781-5afbee80-0327-11eb-9889-414eceecefd2.png)

I recommend we only expand the selection after clicking on an icon, similar to the selection of map layers.

**Comment by nvernooy** [comment]
Only show the temparature and sky icon on the pins, and only open the panel on click

![image](https://user-images.githubusercontent.com/5332516/94905242-d7640e00-049c-11eb-811a-83bce706a5b6.png)
