### ISSUE TITLE
Add image field to collection and dashboard for use in card-based layout in listings

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#199]
Add an image field to a collection and dashboard so that we can use it for a card-based layout when we list collections and dashboards, similar too:

![image](https://user-images.githubusercontent.com/784273/94785114-6a367700-03cf-11eb-82e3-2d4e5694207f.png)

Limit the image size to 640x400. 

Have a look at https://observablehq.com/explore to see how image size changes with screen size.

**Comment by nvernooy** [comment]
Add image upload to collections and dashboards

![image](https://user-images.githubusercontent.com/5332516/94938288-ec5a9480-04d0-11eb-9f04-77224feac2d8.png)
![image](https://user-images.githubusercontent.com/5332516/94938353-01cfbe80-04d1-11eb-9884-8f689932e6d1.png)

**Comment by rochecompaan** [comment]
@nvernooy this is great, thank you! Please note that I requested a card based-layout similar to https://observablehq.com/explore.

In this view, we can fit in a number of cards next to each other on desktop and render fewer columns as screen size decreases.

**Comment by nvernooy** [comment]
Using card based layout

![image](https://user-images.githubusercontent.com/5332516/95107787-a9035e80-073a-11eb-8843-89dd797593fc.png)


![image](https://user-images.githubusercontent.com/5332516/95107864-c3d5d300-073a-11eb-8470-9d3f8424e564.png)

On different screen sizes
![image](https://user-images.githubusercontent.com/5332516/95108059-09929b80-073b-11eb-87bf-168dec9e4784.png)


![image](https://user-images.githubusercontent.com/5332516/95108238-4e1e3700-073b-11eb-85f5-cd701ddd2141.png)

**Comment by rochecompaan** [comment]
@nvernooy this looks absolutely gorgeous!!! 

Can you centre the bar chart icon and make it white, please?

**Comment by rochecompaan** [comment]
Additionally, make the whole image card area clickable.

![image](https://user-images.githubusercontent.com/784273/95114174-d1dc2180-0743-11eb-85c8-99ef7afd9a93.png)

**Comment by nvernooy** [comment]
Awesome, will do

**Comment by nvernooy** [comment]
Updated the icon and clicking on the image will route to the collection/dashboard

![image](https://user-images.githubusercontent.com/5332516/95192961-4ca04d80-07d3-11eb-9762-66286873e2b6.png)
