### ISSUE TITLE
Replace tabs with "gear" icon in top menu bar

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#200]
The tabs don't render well on mobile:

![image](https://user-images.githubusercontent.com/784273/94787365-82f45c00-03d2-11eb-9b53-97824af06a48.png)

Can we replace the tabs with a gear icon in the top menu bar that renders a drop-down menu for each of the tabs instead?

**Comment by nvernooy** [comment]
Replace with gear icon
![image](https://user-images.githubusercontent.com/5332516/94906641-214df380-049f-11eb-95cf-2a9752efb0c3.png)
![image](https://user-images.githubusercontent.com/5332516/94906671-30cd3c80-049f-11eb-8b0a-72c0ff611a41.png)
![image](https://user-images.githubusercontent.com/5332516/94906698-3f1b5880-049f-11eb-89c6-fc71f2db169e.png)

**Comment by rochecompaan** [comment]
@nvernooy double gear icons are visually too confusing. Additionally, I requested that we put the gear icon in the top-most toolbar. Can we replace the icon with an "edit" icon and move it into the toolbar?

![image](https://user-images.githubusercontent.com/784273/94926632-5c611e80-04c1-11eb-9b1b-e7eda9fc8ec0.png)


Additionally, left align the menu items and assign an icon to each "tab" to be consistent with the other menus in the top toolbar.

**Comment by nvernooy** [comment]
Show tabs on desktop view
![image](https://user-images.githubusercontent.com/5332516/95074975-b22b0600-070f-11eb-8272-f284b48215d6.png)

Show icon with dropdown on mobile view
![image](https://user-images.githubusercontent.com/5332516/95075032-ce2ea780-070f-11eb-8ff0-1f063da85066.png)
![image](https://user-images.githubusercontent.com/5332516/95075067-dedf1d80-070f-11eb-8c5c-3284150a63b3.png)
