### ISSUE TITLE
Top margin/padding on mobile too big

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#201]
After the fixes in #189 the top margin/padding on mobile is too big:

![image](https://user-images.githubusercontent.com/784273/94787734-fac28680-03d2-11eb-9ce1-b89aaf1ae63f.png)

**Comment by nvernooy** [comment]
![image](https://user-images.githubusercontent.com/5332516/94906786-607c4480-049f-11eb-84e7-b56a79b24b46.png)
