### ISSUE TITLE
Only show horiz_menu and re-order icons on tap/hover

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#202]
Similar to dashboards, can we only show the horiz_menu and re-order icons on top/hover:

![image](https://user-images.githubusercontent.com/784273/94787920-365d5080-03d3-11eb-9403-074a7e98f4a8.png)

**Comment by nvernooy** [comment]
Only show on hover

![image](https://user-images.githubusercontent.com/5332516/94906856-80136d00-049f-11eb-9e2b-973666d037ea.png)
