### ISSUE TITLE
GIS Maps: Is it possible to set the #of decimals displayed on Pin and on PopUp (two seperate places)

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#208]
I tried here: https://dashtweak.com/dashboards/195/view 
Please show where it can be set.  I guess this will apply for all parameters then i.e. I cannot have Temp = 1 decimal, Wind = 0 decimals, Battery = 1 decimal.
Same applies to decimals used in PopUp

**Comment by GronumSmith** [comment]
It seems to be possible in script 
![image](https://user-images.githubusercontent.com/35992133/95559558-40590200-0a18-11eb-8034-621f23f66660.png)

**Comment by rochecompaan** [comment]
```
icon: 'strong-wind', format: '${value.toFixed(2)} ${unit}</>'
```
