### ISSUE TITLE
Support for influx queries using the results from postgres queries (join)

### ISSUE THREAD

**Issue by etameez** [upfrontsystems/izinto-angular#217]
It is necessary to get  the available sensors on an installation and display forecast/measurement data based on it.

Currently, the influx query will need to be manually created per installation based on sensors available and will need manual adjustment when sensors are added/removed. 

Joining influx and postgres is available in flux (https://docs.influxdata.com/influxdb/v2.0/query-data/flux/sql/) but there is no support
natively in influxql.

**Comment by rochecompaan** [comment]
Is merging the results in Javascript not an option?

**Comment by etameez** [comment]
Looking at it more. I think it makes more sense to do it in javascript as you said.

For posterity, since variables can be sent to queries from html content:  
```
    function loadForecastQuery() {
        var query = {
            'query':
                {
                    'name': 'forecasts_query',
                    'values': {
                        installation_id: installation_id,
                        timeFilter: date_range,
                        query_group_by: time_interval,
                        fields: fields from postgres
                    }
                }
        };
        
        window.top.postMessage(query, '*');
    }
```
