### ISSUE TITLE
Support for Influxdb Flux queries

### ISSUE THREAD

**Issue by jpm-izinto** [upfrontsystems/izinto-angular#219]
https://docs.influxdata.com/influxdb/v1.8/flux/flux-vs-influxql/

**Comment by rochecompaan** [comment]
@jpm-izinto what is the end point for flux queries? Do we still post over http or do we need a client library?

**Comment by jpm-izinto** [comment]
I always use the official Influxdata client libraries, but it seems like the flux queries are still being sent to an http api endpoint:
https://docs.influxdata.com/influxdb/v1.8/guides/query_data/

**Comment by rochecompaan** [comment]
@jpm-izinto this issue is superseded by #230 where we will cover not only Influx but any HTTP data source.
