### ISSUE TITLE
Support Multiple Data Sources for Charts/Single Stat

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#220]
_I guess this has to be seen in the light of possible changes for Charts i.e. use Scripts as for Tables (having said that the current system works quite well and maybe small extensions would be fine)_
Currently multiple queries are supported separated by a simple " ; " in the Query Field. 
However: On,ly one data source is allowed per chart, it would be great to have a link between a query and a data source.  or spec the source in query .. although that is easiest from a dev pov Making it more user friendly i.e. select from a dropdown is preferred imo,
![image](https://user-images.githubusercontent.com/35992133/99077045-d0184000-25c4-11eb-8c1e-7254cf9eb270.png)

**Comment by rochecompaan** [comment]
@GronumSmith I don't think it makes sense for us to support multiple data sources on the old charts and single stats. It would be time better spent creating script versions for charts and single stats that use the current query infrastructure.
