### ISSUE TITLE
Two Scrollbars : Remove one ?

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#221]
Note: This has been discussed "somewhere" could not find now here in Github. I also suspect it is a bigger issue/visible in Linux (@jpm-izinto ??)
There are two scroll bars and especially when not visible one can easily scroll on the wrong one. 

It might be that both are required (e.g. one is to scroll down charts, the other is to access the header for displaying the date selector)

**Comment by jpm-izinto** [comment]
@GronumSmith the issue I had was solved (https://github.com/upfrontsystems/izinto-angular/issues/189). Can you please add a screenshot here so that we can see what you are talking about?

**Comment by GronumSmith** [comment]
There was a problem with uploading an image to GitHub when I logged the issue, then got sidetracked and forgot to try again.  I only saw it when one does "Inspect Element" on Chrome.  2 bars were displayed and I recalled you mentioned/logged.  But if it is resolved (not manifesting itself) we can resolve. (again ;-)
