### ISSUE TITLE
Refactor user access

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#226]
Please refactor user access as follows:

- All users can create collections and dashboards ***
- When a user creates content, they automatically have an Administrator role on that content
- Only an Administrator can give access to other users
- The Administrator of the content can share an "Admin", "Edit" or "View" role with a user on Collection or Dashboard level
- A user with "Edit" permission can edit all content but can't add any new content.
- A user with "View" permission can only view content.
- A user with "Admin" has the same rights as the user that created the content.

*** This will be installation dependent. You might have a white-labelled instance where you disable content creation by users and only allow Administrators of the system to create it, similar to what we have now.

@GronumSmith @jpm-izinto @nvernooy comments and questions?

**Comment by GronumSmith** [comment]
Thanks Roche.  This seems good and logical. I know that you would like to follow GoogleDocs model and I assume you follow roughly what they do in this proposal (and it would make sense).  The one thing that I beleive is different for us/business model is the idea of "Teams" or "Groups" which would reduce admin greatly! I don't know if Google Offers something like that. I can also imagine that what you suggest here is (a) a first step (b) can still apply when the idea of Groups is added.  I am also not sure where the management/setting of Groups will be done.

**Comment by rochecompaan** [comment]
@GronumSmith, yes Teams and Groups would be a different feature altogether. We can certainly create an issue for that for future dev.

**Comment by jpm-izinto** [comment]
We might need to think about groups/teams and how they will integrate with other systems. Please see my comment about Keycloak here https://github.com/upfrontsystems/izinto-angular/issues/224#issuecomment-739803336

**Comment by rochecompaan** [comment]
@jpm-izinto I see authorization as separate to user access to content. Perhaps "content access" would have been a better title for this issue. At the moment our source for users is still limited to the DashTweak database but we will definitely look at integrating services like Firebase Auth, Auth0 or Keycloak soon.

**Comment by jpm-izinto** [comment]
Content access, yes. For me the main thing to think about is how and where do we keep a central list that defines what users may see.

On Izinto's side we have Sites and every Site has many Installations. We would likely want to give a User, or a Group of Users access to a Site.

On DashTweak's side a User will have access to Collections and Dashboards.

Somehow we need to bring these two concepts together. And the access permissions need to be defined where multiple systems can access them, so that we do not need to maintain multiple lists of access permissions.

Still a few things to think about, and likely we will need to discuss this to find the best approach.

**Comment by rochecompaan** [comment]
I think you will have to do some API-level integration at some point to keep Django and Dashtweak in sync and to automate client on-boarding.

**Comment by nvernooy** [comment]
Added a user access tab to collections and dashboards where permissions can be set per user

![image](https://user-images.githubusercontent.com/5332516/102115257-fb03e700-3e43-11eb-96a3-39e21a345d67.png)
![image](https://user-images.githubusercontent.com/5332516/102116101-24714280-3e45-11eb-840f-be7dc895309a.png)


Users with admin rights can add, edit and delete collections and dashboards, and the items in dashboards

![image](https://user-images.githubusercontent.com/5332516/102115700-95642a80-3e44-11eb-8193-a6d1ac0c34b1.png)

Users with edit rights can only edit existing items, but cannot add or delete. Users with view permission can see the item but not make any changes to it.

![image](https://user-images.githubusercontent.com/5332516/102115840-c6dcf600-3e44-11eb-9f49-a3e2fc1c26bf.png)
