### ISSUE TITLE
Wind arrow chart broken

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#32]
I have a wind arrow chart that doesn't seem to work anymore. The query is
```
SELECT mean("windDirection") FROM "izintorain"."autogen"."measurement" WHERE ("dev_id" ='1406300003') AND time >= now() - :range: GROUP BY time(1d), "dev_id" fill(none)
```

All I see is:
![image](https://user-images.githubusercontent.com/784273/73825479-aeec1d00-4804-11ea-8655-662fef81b58d.png)

**Comment by GronumSmith** [comment]
Please have a look at Wind Chart.  They are broken (strange/bad behaviour)
https://dashtweak.com/dashboards/15 
On day view there are no bars 
![image](https://user-images.githubusercontent.com/35992133/90220822-3c8a7400-de09-11ea-84dd-d40ed35ea4cb.png)
On Month some rendering is wrong: 
![image](https://user-images.githubusercontent.com/35992133/90220865-5330cb00-de09-11ea-9014-a82d5db80088.png)
 
BTW: What about the OPTION ;-) to use lines for wind strength.  It is probably cleaner and less prone to these Bar problems (we have a Bar-problem ;-)) 
here as YR does it
![image](https://user-images.githubusercontent.com/35992133/90221046-b28edb00-de09-11ea-98ee-fe44912e445c.png)

**Comment by rochecompaan** [comment]
@GronumSmith, I also like the line option! It shouldn't be that hard to switch to a line instead.

**Comment by nvernooy** [comment]
Changed the wind chart to use line chart and move the arrows below the line

![image](https://user-images.githubusercontent.com/5332516/90389897-ab2a3480-e08a-11ea-860b-516b8178064f.png)

**Comment by GronumSmith** [comment]
Please check: 
When AUTO is used for Group By Intervals 
The Chart is OK (in that Arrows are where they should be, but obviously the Auto here does not have enough resolution (Grouping is too wide)
![image](https://user-images.githubusercontent.com/35992133/90505443-ec861700-e152-11ea-982a-d7872945f0b4.png)
However when using "a better" Group By 
![image](https://user-images.githubusercontent.com/35992133/90505521-0b84a900-e153-11ea-9211-72861373d7e5.png)
The Chart is broken i.e. arrows are at top and all in same direction. 
![image](https://user-images.githubusercontent.com/35992133/90505227-8b5e4380-e152-11ea-8e2a-b9fa5b616fd2.png)

For some values is seems to work e.g.
![image](https://user-images.githubusercontent.com/35992133/90505643-41299200-e153-11ea-87a6-f3fce085afe4.png)
 and Day Time Range selector 
![image](https://user-images.githubusercontent.com/35992133/90505696-5d2d3380-e153-11ea-8b67-2daf130d856c.png)

But for others not e.g.
![image](https://user-images.githubusercontent.com/35992133/90505865-9e254800-e153-11ea-9aa9-46f96f8d575b.png)
![image](https://user-images.githubusercontent.com/35992133/90505908-b72df900-e153-11ea-967e-565666425f7e.png)

**Comment by rochecompaan** [comment]
@nvernooy, this seems fixed for month:

![image](https://user-images.githubusercontent.com/784273/90506595-d6795600-e154-11ea-95f0-74b4b696856c.png)

But it is still broken on the week chart:

![image](https://user-images.githubusercontent.com/784273/90506648-ebee8000-e154-11ea-9203-29577ef6b5be.png)

It renders correctly on the day chart, but it renders too many arrows:

![image](https://user-images.githubusercontent.com/784273/90506748-0c1e3f00-e155-11ea-8af9-413950b0dacf.png)

Try and calculate the number of arrows using the screen width. Eg if the chart is 800 wide, we can only fit in 800 / 40 = 20. This is assuming the arrow plus padding is 40 px wide. Please check what width works best.

**Comment by nvernooy** [comment]
Fixed the group by intervals for wind arrow charts

Fixed the spacing and amount of arrows for all view and group by options

![image](https://user-images.githubusercontent.com/5332516/90617013-76df8100-e20e-11ea-9ad6-d4fe0a66a3f4.png)

![image](https://user-images.githubusercontent.com/5332516/90617213-b1e1b480-e20e-11ea-8821-5c414cbeafd2.png)

![image](https://user-images.githubusercontent.com/5332516/90617334-d9388180-e20e-11ea-951f-6ef02209aca4.png)

**Comment by rochecompaan** [comment]
Working nicely now!
