### ISSUE TITLE
Multi line graphs - multiple possible queries

### ISSUE THREAD

**Issue by jpm-izinto** [upfrontsystems/izinto-angular#33]
# Verskillende paremeters op selfde device

```
SELECT mean("windGust") AS "mean_windGust", mean("wind") AS "mean_wind" FROM "izintorain"."autogen"."measurement" WHERE time > :dashboardTime: AND "dev_id"='station_001' GROUP BY time(:interval:) FILL(null)
```

![image](https://user-images.githubusercontent.com/54270670/73847404-e2dc3800-482e-11ea-9053-612e5df1d135.png)

## Result
single line

![image](https://user-images.githubusercontent.com/54270670/73847789-9f35fe00-482f-11ea-9f53-ef96816e387f.png)

# Selfde parameter op verskillende devices

```
SELECT mean("wind") AS "mean_wind" FROM "izintorain"."autogen"."measurement" WHERE time > :dashboardTime: AND ("dev_id"='station_001' OR "dev_id"='1406300020') GROUP BY time(:interval:), dev_id FILL(null)
```

![image](https://user-images.githubusercontent.com/54270670/73847477-07d0ab00-482f-11ea-996d-fe547cb390f4.png)

## Result
as expected

![image](https://user-images.githubusercontent.com/54270670/73847818-ad841a00-482f-11ea-8d1a-60eb3ff49d38.png)

# Aggregations: chill units

```
SELECT cumulative_sum(sum("chill_units_dpcu")) AS "mean_chill_units_dpcu", cumulative_sum(sum("chill_units_dynamic")) AS "mean_chill_units_dynamic", cumulative_sum(sum("chill_units_dynamic_interE")) AS "mean_chill_units_dynamic_interE", cumulative_sum(sum("chill_units_dynamic_xi")) AS "mean_chill_units_dynamic_xi", cumulative_sum(sum("chill_units_infruitec")) AS "mean_chill_units_infruitec", cumulative_sum(sum("chill_units_richardson")) AS "mean_chill_units_richardson" FROM "izinto_aggregations"."autogen"."aggregation" WHERE time > :dashboardTime: AND "dev_id"='1406300020' GROUP BY time(:interval:) FILL(null)
```

![image](https://user-images.githubusercontent.com/54270670/73847141-5762a700-482e-11ea-8477-f5f0e4ead14c.png)

## Result
empty graph

![image](https://user-images.githubusercontent.com/54270670/73848099-21262700-4830-11ea-8aae-c6e6890b2c3d.png)

# Aggregations: rain

```
SELECT cumulative_sum(sum("rain")) AS "mean_rain" FROM "izinto_aggregations"."autogen"."aggregation" WHERE time > :dashboardTime: AND "dev_id"='station_001' GROUP BY time(:interval:) FILL(null)
```

![image](https://user-images.githubusercontent.com/54270670/73847314-adcfe580-482e-11ea-9055-be1605996fb2.png)

## Result
as expected

![image](https://user-images.githubusercontent.com/54270670/73848201-59c60080-4830-11ea-974c-d9f609ea1643.png)

# Rain single stat

```
SELECT sum("rain") AS "sum_rain" FROM "izinto_aggregations"."autogen"."aggregation" WHERE time > :dashboardTime: AND "dev_id"='station_001'
```

![image](https://user-images.githubusercontent.com/54270670/73848667-36e81c00-4831-11ea-9fb0-47812c00c62d.png)

## Result
as expected

![image](https://user-images.githubusercontent.com/54270670/73848974-cab9e800-4831-11ea-81a3-b85439d1051b.png)

**Comment by rochecompaan** [comment]
@nvernooy can we please add support for multiple queries separated with a semi-colon. See previous comments for examples.

**Comment by nvernooy** [comment]
Added support for multiple queries in one chart
Using the query

> SELECT mean("temperature") AS "mean_temperature" FROM "izintorain"."autogen"."measurement" WHERE "dev_id"='station_001' AND :range: group by time(:group_by:) FILL(null); 
> SELECT mean("humidity") AS "mean_humidity" FROM "izintorain"."autogen"."measurement" WHERE "dev_id"='1406300020' AND :range: group by time(:group_by:) FILL(null)

Produced the chart

![image](https://user-images.githubusercontent.com/5332516/90630614-a350c880-e221-11ea-8131-8e08f0649fb3.png)

**Comment by GronumSmith** [comment]
Thanks Neil
I have tried exactly this (script) on 
https://dashtweak.com/dashboards/144 
but does not seem to work.  Please check/comment

**Comment by rochecompaan** [comment]
@GronumSmith I haven't released this yet, this is why the issue is still open. I'll deploy it quickly.

**Comment by rochecompaan** [comment]
It seems to work now:

![image](https://user-images.githubusercontent.com/784273/90646226-46f8a380-e237-11ea-9106-10669eb6ba04.png)

There is an issue with the y-axis scaling when there is no data for one query, but I'll create a separate issue for that.
