### ISSUE TITLE
Single Stat (Visualization improvements) Specify Size 

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#72]
Single stat widgets are very flat. Make them by default a golden rectangle, but make it configurable in the future.
I guess this can go with (i.e. +- same code) the ability to change the height/size of a chart? 
@jpm-izinto add if you like

**Comment by rochecompaan** [comment]
Font size for single stats is now completely responsive.

![image](https://user-images.githubusercontent.com/784273/92441339-515eeb00-f1ae-11ea-982e-f698cca1e8aa.png)

![image](https://user-images.githubusercontent.com/784273/92441371-62a7f780-f1ae-11ea-8452-4b8ddc06f6db.png)

![image](https://user-images.githubusercontent.com/784273/92441418-79e6e500-f1ae-11ea-8e79-f36f408f281b.png)

![image](https://user-images.githubusercontent.com/784273/92441459-8a975b00-f1ae-11ea-85cb-5626f40c787d.png)
