### ISSUE TITLE
Different Text Sizes on Chart: Legend smaller and Value a bit smaller? 

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#98]
Although some old farmers eyesight might be a problem if one compares the text size on this graph it varies quite a lot. I would make date/time (above graph) same as the legend. And the value same as legend but in bold.  Enough of an emphasis on the value?

![image](https://user-images.githubusercontent.com/35992133/78472697-35f13f00-773b-11ea-84e5-e0fba0e77ae5.png)

**Comment by rochecompaan** [comment]
@nvernooy, can we please change the font-size of the date, ticks and legends to 12px?

**Comment by nvernooy** [comment]
Set font size of date, ticks and legends

![image](https://user-images.githubusercontent.com/5332516/94696547-73740500-0337-11eb-91b6-789c5f64d77c.png)
![image](https://user-images.githubusercontent.com/5332516/94696911-db2a5000-0337-11eb-80a7-af87fe7a07ec.png)

**Comment by GronumSmith** [comment]
yes this seems to have been a duplication of Issues. Apologies.
