### ISSUE TITLE
Use more common text size but colours and BOLD to emphasise info

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#99]
I do appreciate emphasising some info (with text size/bold/colour) but if it varies too much I think it can overwhelm the eye.  Maybe use bold and colour more and less the variance in text size?

![image](https://user-images.githubusercontent.com/35992133/78472737-849ed900-773b-11ea-94a8-3a0536a9c41f.png)

**Comment by rochecompaan** [comment]
The font-size is much better now. I think we can close this issue.

**Comment by GronumSmith** [comment]
I have refreshed numerous times on mobile, pc, chrome firefox but I keep getting 
![image](https://user-images.githubusercontent.com/35992133/94779818-d01f0080-03c7-11eb-9fad-d98f385991af.png)
Is this correct? 
Was the Legend(s) not also supposed to be same font size as X- Y- axis text?

**Comment by rochecompaan** [comment]
This issue was for the single stat font-size, not the font-size changes we discussed in #98
